import base64
import json
import os
import threading
import time
from datetime import datetime
from typing import Dict, List, Optional

import numpy as np
from pydantic import BaseModel

from imswitch.imcommon.framework import Signal
from imswitch.imcommon.model import APIExport, dirtools, initLogger
from ..basecontrollers import ImConWidgetController

try:
    import cv2
    HAS_CV2 = True
except ImportError:
    HAS_CV2 = False

try:
    import tifffile
    HAS_TIFFFILE = True
except ImportError:
    HAS_TIFFFILE = False


class StageMapParams(BaseModel):
    """Parameters for the stage map (MicroMagellan-style live stitching)."""
    # Capture behaviour
    autoSnapEnabled: bool = True        # snap automatically when the stage settled at a new spot
    minMoveFraction: float = 0.35       # min displacement (fraction of the smaller FOV side) to trigger a new tile
    settleTimeS: float = 0.25           # stage must be stationary for this long before a snap
    positionPollS: float = 0.15         # position polling interval
    frameTimeoutS: float = 2.0          # max time to wait for a fresh frame after settling

    # Preview (what is pushed to the frontend)
    previewMaxSize: int = 384           # longest side of the downscaled preview tile in px
    previewQuality: int = 80            # JPEG quality of preview tiles

    # Storage
    saveRawTiles: bool = True           # store full-resolution raw frames on disk
    mapName: str = ""                   # session name; autogenerated when empty

    # Optics; 0 means "read from detector"
    pixelSizeUm: float = 0.0

    # Channel handling
    activeChannel: str = ""             # empty = auto-detect from enabled illumination

    class Config:
        arbitrary_types_allowed = True


class StageMapStatus(BaseModel):
    """Runtime status of the stage map."""
    isRunning: bool = False
    sessionPath: str = ""
    tileCount: int = 0
    channels: List[str] = []
    activeChannel: str = ""
    pixelSizeUm: float = 1.0
    fovX: float = 0.0                   # camera FOV in µm
    fovY: float = 0.0
    positionX: float = 0.0
    positionY: float = 0.0
    detectorName: str = ""
    lastError: str = ""

    class Config:
        arbitrary_types_allowed = True


def prescanLayout(spanUm: float, dxUm: float, pixelSizeUm: float, frameShape,
                  subsample: int, maxStripBytes: int, itemsize: int = 2):
    """How one prescan line is laid out: the sample slots and the strip they fill.

    A slot is one camera exposure, ``dxUm`` apart along the sweep, and it fills
    exactly the strip columns it covers, so the strip is contiguous whatever the
    speed. The strip is built ``subsample`` times coarser than the camera —
    this is a locator, and a 10 mm line at 0.12 µm/px would be 80 000 columns —
    and the factor grows until the strip fits ``maxStripBytes``.

    Returns (slots, stripW, stripH, subsample, dxUm) with ``dxUm`` clamped to
    the frame width: a pitch wider than the field would leave gaps.
    """
    frameH, frameW = int(frameShape[0]), int(frameShape[1])
    pixelSizeUm = max(float(pixelSizeUm), 1e-6)
    fieldUm = max(1, frameW) * pixelSizeUm
    dxUm = fieldUm if dxUm <= 0 else min(max(float(dxUm), pixelSizeUm), fieldUm)
    slots = max(2, int(np.ceil(spanUm / dxUm)))
    subsample = max(1, int(subsample))
    while True:
        scale = pixelSizeUm * subsample
        stripW = max(2, int(np.ceil(spanUm / scale)))
        stripH = max(1, len(range(0, frameH, subsample)))
        if stripW * stripH * itemsize <= maxStripBytes or subsample >= 64:
            return slots, stripW, stripH, subsample, dxUm
        subsample += 1


class _NonBlockingMove:
    """Run one blocking stage move on a thread so the caller can grab frames.

    The stage API only offers a blocking move; every controller that needs to
    acquire *during* a move has grown its own copy of this. This one is
    deliberately local — importing another controller to borrow a helper drags
    an entire unrelated module in with it.
    """

    def __init__(self, stage, value, axis, speed):
        self._stage = stage
        self._value = value
        self._axis = axis
        self._speed = speed
        self.finished = False
        self.error: Optional[str] = None
        self._thread: Optional[threading.Thread] = None

    def start(self):
        self._thread = threading.Thread(target=self._run, daemon=True,
                                        name="StageMapPrescanMove")
        self._thread.start()

    def _run(self):
        try:
            self._stage.move(value=self._value, axis=self._axis, speed=self._speed,
                             is_absolute=False, is_blocking=True)
        except Exception as e:
            # Never leave the polling loop spinning on a move that died.
            self.error = str(e)
        finally:
            self.finished = True

    def join(self, timeout=None):
        if self._thread is not None:
            self._thread.join(timeout)


class StageMapController(ImConWidgetController):
    """MicroMagellan/Google-Maps-style stage mapping.

    While mapping is running, the controller watches the stage position.
    Whenever the stage comes to rest at a spot that is not covered yet
    (or covered by an older tile), it grabs a camera frame, stores the raw
    frame on disk, and pushes a downscaled JPEG preview to the frontend via
    the ``sigStageMapTileAdded`` socket signal. The frontend places the
    previews on a pan/zoom canvas in stage coordinates, so a stitched map
    grows wherever the user moves — no extra stage movement is generated.

    The full-resolution tiles can be fused into a multi-channel stitched
    OME-TIFF via ``saveStitchedOmeTiff``.
    """

    sigStageMapTileAdded = Signal(dict)
    sigStageMapStatus = Signal(dict)

    MAX_STITCH_PIXELS = 1.2e9  # safety cap for the stitched canvas (bytes ~ 2x for uint16)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._logger = initLogger(self)

        self.params = StageMapParams()

        # Hardware
        self._detector = None
        self._detectorName = ""
        self._stage = None
        self._initializeHardware()

        # Session/tile state
        self._tiles: List[Dict] = []          # metadata for every captured tile
        self._tilesLock = threading.Lock()
        self._sessionPath: Optional[str] = None
        self._acqHandle = None

        # Mapping thread state
        self._isRunning = False
        self._shouldStop = threading.Event()
        self._monitorThread: Optional[threading.Thread] = None
        self._snapRequested = threading.Event()
        self._prescanThread: Optional[threading.Thread] = None
        self._lastError = ""

        self._logger.info("StageMapController initialized")

    # ------------------------------------------------------------------ #
    # Hardware helpers
    # ------------------------------------------------------------------ #

    def _initializeHardware(self):
        try:
            detectorNames = self._master.detectorsManager.getAllDeviceNames()
            if detectorNames:
                try:
                    self._detectorName = self._master.detectorsManager.getCurrentDetectorName()
                except Exception:
                    self._detectorName = detectorNames[0]
                self._detector = self._master.detectorsManager[self._detectorName]
        except Exception as e:
            self._logger.warning(f"No detector available for stage map: {e}")

        try:
            positionerNames = self._master.positionersManager.getAllDeviceNames()
            if positionerNames:
                self._stage = self._master.positionersManager[positionerNames[0]]
        except Exception as e:
            self._logger.warning(f"No positioner available for stage map: {e}")

    def _getPixelSizeUm(self) -> float:
        if self.params.pixelSizeUm and self.params.pixelSizeUm > 0:
            return float(self.params.pixelSizeUm)
        try:
            # DetectorManager.pixelSizeUm is [Z, Y, X]
            ps = self._detector.pixelSizeUm
            pixelSize = float(ps[-1])
            if pixelSize > 0:
                return pixelSize
        except Exception:
            pass
        return 1.0

    def _getStagePositionXY(self) -> Optional[List[float]]:
        try:
            pos = self._stage.getPosition()
            return [float(pos.get("X", 0.0)), float(pos.get("Y", 0.0))]
        except Exception as e:
            self._logger.error(f"Could not read stage position: {e}")
            return None

    def _getActiveChannel(self) -> str:
        """Explicit channel wins; otherwise derive from enabled illumination."""
        if self.params.activeChannel:
            return self.params.activeChannel
        try:
            for laserName in self._master.lasersManager.getAllDeviceNames():
                laser = self._master.lasersManager[laserName]
                if getattr(laser, "enabled", False):
                    return str(laserName)
        except Exception:
            pass
        return "default"

    def _grabFreshFrame(self) -> Optional[np.ndarray]:
        """Grab a frame that was exposed after the stage settled."""
        if self._detector is None:
            return None
        try:
            if hasattr(self._detector, "flushBuffer"):
                self._detector.flushBuffer()
            elif hasattr(self._detector, "flushBuffers"):
                self._detector.flushBuffers()
        except Exception:
            pass

        timeout = max(0.2, float(self.params.frameTimeoutS))
        t0 = time.time()
        lastFrameNumber = -1
        frame = None
        while time.time() - t0 < timeout:
            try:
                frame, frameNumber = self._detector.getLatestFrame(returnFrameNumber=True)
            except TypeError:
                # Detector does not support frame numbers - accept the latest frame
                frame = self._detector.getLatestFrame()
                if frame is not None:
                    return frame
                time.sleep(0.02)
                continue
            except Exception as e:
                self._logger.error(f"Error grabbing frame: {e}")
                return None
            if frame is not None and frameNumber is not None:
                if lastFrameNumber == -1:
                    lastFrameNumber = frameNumber
                elif frameNumber > lastFrameNumber:
                    return frame
            time.sleep(0.02)
        return frame

    # ------------------------------------------------------------------ #
    # Session / storage
    # ------------------------------------------------------------------ #

    def _createSession(self):
        name = self.params.mapName.strip() or datetime.now().strftime("stagemap_%Y%m%d_%H%M%S")
        base = os.path.join(dirtools.UserFileDirs.getValidatedDataPath(), "StageMapController", name)
        os.makedirs(os.path.join(base, "raw"), exist_ok=True)
        self._sessionPath = base
        with self._tilesLock:
            self._tiles = []
        self._writeTileIndex()
        self._logger.info(f"Stage map session created at {base}")

    def _writeTileIndex(self):
        if not self._sessionPath:
            return
        try:
            with self._tilesLock:
                index = {
                    "pixelSizeUm": self._getPixelSizeUm(),
                    "tiles": [
                        {k: v for k, v in t.items() if k != "preview"}
                        for t in self._tiles
                    ],
                }
            with open(os.path.join(self._sessionPath, "tiles.json"), "w") as f:
                json.dump(index, f, indent=2)
        except Exception as e:
            self._logger.error(f"Could not write tile index: {e}")

    def _trimTiles(self):
        """Drop the oldest previews once the map gets large.

        Each tile carries a base64 JPEG in RAM, and mapping runs for as long as
        the operator leaves it on. The metadata is kept (tiles.json on disk has
        everything); only the in-memory image of the oldest tiles is released.
        Call with _tilesLock held.
        """
        withPreview = [t for t in self._tiles if t.get("preview")]
        excess = len(withPreview) - self.MAX_TILE_PREVIEWS
        for tile in withPreview[:max(0, excess)]:
            tile["preview"] = None

    def _makePreview(self, frame: np.ndarray) -> Optional[str]:
        """Downscale + JPEG-encode a frame, return base64 string."""
        try:
            img = frame
            if img.ndim == 3:
                # colour camera: keep as-is (assume BGR/RGB uint8)
                pass
            maxSide = max(img.shape[0], img.shape[1])
            scale = min(1.0, float(self.params.previewMaxSize) / maxSide)
            if HAS_CV2:
                if scale < 1.0:
                    img = cv2.resize(
                        img,
                        (max(1, int(img.shape[1] * scale)), max(1, int(img.shape[0] * scale))),
                        interpolation=cv2.INTER_AREA,
                    )
                # normalize to 8 bit for the preview
                if img.dtype != np.uint8:
                    img = img.astype(np.float32)
                    lo, hi = np.percentile(img, (1, 99.8))
                    if hi <= lo:
                        hi = lo + 1
                    img = np.clip((img - lo) / (hi - lo) * 255.0, 0, 255).astype(np.uint8)
                ok, buf = cv2.imencode(
                    ".jpg", img, [int(cv2.IMWRITE_JPEG_QUALITY), int(self.params.previewQuality)]
                )
                if not ok:
                    return None
                return base64.b64encode(buf.tobytes()).decode("ascii")
            else:
                # numpy-only fallback: subsample + PNG via tifffile is overkill; use PIL if present
                from PIL import Image
                import io
                if scale < 1.0:
                    step = max(1, int(round(1.0 / scale)))
                    img = img[::step, ::step]
                if img.dtype != np.uint8:
                    img = img.astype(np.float32)
                    lo, hi = np.percentile(img, (1, 99.8))
                    if hi <= lo:
                        hi = lo + 1
                    img = np.clip((img - lo) / (hi - lo) * 255.0, 0, 255).astype(np.uint8)
                pil = Image.fromarray(img)
                bio = io.BytesIO()
                pil.save(bio, format="JPEG", quality=int(self.params.previewQuality))
                return base64.b64encode(bio.getvalue()).decode("ascii")
        except Exception as e:
            self._logger.error(f"Could not create preview: {e}")
            return None

    # ------------------------------------------------------------------ #
    # Tile capture
    # ------------------------------------------------------------------ #

    def _captureTile(self, position: List[float]) -> bool:
        frame = self._grabFreshFrame()
        if frame is None:
            self._lastError = "No frame received from detector"
            self._logger.warning(self._lastError)
            return False

        pixelSize = self._getPixelSizeUm()
        channel = self._getActiveChannel()
        heightPx, widthPx = frame.shape[0], frame.shape[1]
        widthUm = widthPx * pixelSize
        heightUm = heightPx * pixelSize

        with self._tilesLock:
            tileId = len(self._tiles)

        rawPath = ""
        if self.params.saveRawTiles and self._sessionPath and HAS_TIFFFILE:
            try:
                safeChannel = "".join(c if c.isalnum() else "_" for c in channel)
                rawPath = os.path.join(
                    self._sessionPath, "raw",
                    f"tile_{tileId:05d}_{safeChannel}.tif",
                )
                tifffile.imwrite(
                    rawPath,
                    frame,
                    metadata={
                        "PositionX_um": position[0],
                        "PositionY_um": position[1],
                        "PixelSize_um": pixelSize,
                        "Channel": channel,
                    },
                )
            except Exception as e:
                self._logger.error(f"Could not save raw tile: {e}")
                rawPath = ""

        preview = self._makePreview(frame)

        tile = {
            "id": tileId,
            # centre of the FOV in stage coordinates (µm)
            "x": float(position[0]),
            "y": float(position[1]),
            "widthUm": float(widthUm),
            "heightUm": float(heightUm),
            "channel": channel,
            "rawPath": rawPath,
            "timestamp": time.time(),
            "preview": preview,
        }
        with self._tilesLock:
            self._tiles.append(tile)
            self._trimTiles()
        self._writeTileIndex()

        if preview is not None:
            self.sigStageMapTileAdded.emit({
                "id": tileId,
                "x": tile["x"],
                "y": tile["y"],
                "widthUm": tile["widthUm"],
                "heightUm": tile["heightUm"],
                "channel": channel,
                "image": preview,
                "format": "jpeg",
            })
        self._emitStatus()
        return True

    # ------------------------------------------------------------------ #
    # Prescan
    # ------------------------------------------------------------------ #

    # Newest tiles whose preview image stays in RAM (see _trimTiles).
    MAX_TILE_PREVIEWS = 600

    # The strip is the only buffer a line holds; past this it is built coarser.
    PRESCAN_MAX_STRIP_MB = 64
    # Camera pixels per strip pixel when the caller does not say.
    PRESCAN_SUBSAMPLE = 4


    def _prescanLoop(self, minX, maxX, minY, maxY, dy, speedX, objectiveSlot,
                     dx, subsample):
        """One continuous X sweep per Y line, each pushed as one wide tile.

        Lines alternate direction (serpentine): the stage is already at the far
        end when a line finishes, so driving straight back across it halves the
        travel. Each strip is emitted as soon as its line ends, so the map fills
        in line by line rather than at the end.
        """
        acqHandle = None
        restore = self._enterPrescanOptics(objectiveSlot)
        try:
            try:
                acqHandle = self._master.detectorsManager.startAcquisition()
            except Exception as e:
                self._logger.warning(f"Could not start acquisition: {e}")

            y = minY
            forward = True
            while y <= maxY + 1e-6 and not self._shouldStop.is_set():
                startX, endX = (minX, maxX) if forward else (maxX, minX)
                result = self._prescanLine(startX, endX, y, speedX, dx, subsample)
                if result is not None:
                    strip, stripPixelSize = result
                    if not forward:
                        # Store every strip left-to-right whichever way it was
                        # driven, so the map does not mirror alternate lines.
                        strip = strip[:, ::-1]
                    self._addStrip(strip, minX, maxX, y, stripPixelSize)
                forward = not forward
                y += dy
        except Exception as e:
            self._lastError = f"Prescan failed: {e}"
            self._logger.error(self._lastError)
        finally:
            if acqHandle is not None:
                try:
                    self._master.detectorsManager.stopAcquisition(acqHandle)
                except Exception:
                    pass
            self._restorePrescanOptics(restore)
            self._prescanThread = None
            self._emitStatus()
            self._logger.info("Prescan finished")

    def _objectiveController(self):
        try:
            return self._master.getController("Objective")
        except Exception:
            return None

    def _enterPrescanOptics(self, objectiveSlot: Optional[int]) -> Dict:
        """Remember where we were, then move to the prescan objective.

        Returns what _restorePrescanOptics needs to put everything back: the
        prescan is a detour, and the operator should find the stage and the
        turret exactly where they left them.
        """
        state: Dict = {"xyz": None, "slot": None}
        try:
            pos = self._stage.getPosition()
            state["xyz"] = (float(pos.get("X", 0.0)), float(pos.get("Y", 0.0)),
                            float(pos.get("Z", 0.0)))
        except Exception as e:
            self._logger.warning(f"Could not read stage position to restore later: {e}")

        if objectiveSlot is None:
            return state

        objective = self._objectiveController()
        if objective is None:
            self._logger.warning("No objective controller — prescan runs on the current lens")
            return state

        try:
            current, _ = objective.getCurrentObjective()
            if current == objectiveSlot:
                return state
            self._logger.info(f"Prescan: switching objective {current} -> {objectiveSlot}")
            # skipZ=False so the turret's own saved focus for that lens is
            # applied — that is the refocus, and it is the only one available
            # without a sample-dependent autofocus.
            objective.moveToObjective(slot=objectiveSlot, skipZ=False)
            self._waitForObjective(objective)
            state["slot"] = current
        except Exception as e:
            self._logger.error(f"Could not switch objective for prescan: {e}")
        return state

    def _restorePrescanOptics(self, state: Dict):
        objective = self._objectiveController()
        if state.get("slot") is not None and objective is not None:
            try:
                self._logger.info(f"Prescan: restoring objective {state['slot']}")
                objective.moveToObjective(slot=state["slot"], skipZ=False)
                self._waitForObjective(objective)
            except Exception as e:
                self._logger.error(f"Could not restore objective: {e}")

        xyz = state.get("xyz")
        if xyz is not None:
            try:
                x, y, z = xyz
                if "XY" in (getattr(self._stage, "combinedAxes", None) or []):
                    self._stage.move(value=(x, y), axis="XY", is_absolute=True, is_blocking=True)
                else:
                    self._stage.move(value=x, axis="X", is_absolute=True, is_blocking=True)
                    self._stage.move(value=y, axis="Y", is_absolute=True, is_blocking=True)
                self._stage.move(value=z, axis="Z", is_absolute=True, is_blocking=True)
            except Exception as e:
                self._logger.error(f"Could not restore stage position: {e}")

    def _waitForObjective(self, objective, timeout: float = 60.0):
        """The turret move runs on its own thread; wait for it to settle."""
        deadline = time.time() + timeout
        while time.time() < deadline:
            if not getattr(objective, "_isMovingObjective", False):
                return True
            time.sleep(0.1)
        self._logger.warning("Objective move did not finish in time")
        return False

    def _centreBand(self, frame: np.ndarray, widthPx: int, subsample: int) -> np.ndarray:
        """The centre ``widthPx`` camera columns of a frame, ``subsample`` times coarser.

        The stage never stops, so only the middle of each frame corresponds to
        the position we recorded. Copied so the detector can reuse its buffer.
        """
        if frame.ndim == 3:
            frame = frame[:, :, 0]
        width = frame.shape[1]
        band = max(1, min(width, widthPx))
        start = max(0, width // 2 - band // 2)
        return np.array(frame[::subsample, start:start + band:subsample], copy=True)

    def _prescanLine(self, startX, endX, y, speedX, dx, subsample):
        """Drive X once; return the strip of one exposure per ``dx`` and its µm/px.

        Sampling is on a clock, not on distance polled: with the sweep assumed
        at constant speed, exposure k is due ``k·dx/speedX`` after the start
        and fills the strip columns slot k covers. Nothing is buffered but the
        strip itself, built ``subsample`` times coarser than the camera.
        ``startX``/``endX`` are the ends in travel order, so on a return line
        startX > endX; everything below works in distance travelled.
        """
        if "XY" in (getattr(self._stage, "combinedAxes", None) or []):
            self._stage.move(value=(startX, y), axis="XY", is_absolute=True, is_blocking=True)
        else:
            self._stage.move(value=startX, axis="X", is_absolute=True, is_blocking=True)
            self._stage.move(value=y, axis="Y", is_absolute=True, is_blocking=True)

        pixelSize = self._getPixelSizeUm()
        span = abs(endX - startX)
        # A (1, 1) fallback here would clamp dx to one pixel and schedule an
        # exposure every few microseconds; learn the real shape from a frame.
        frameShape = getattr(self._detector, "shape", None)
        if not frameShape or min(frameShape[:2]) < 2:
            probe = self._detector.getLatestFrame()
            frameShape = probe.shape[:2] if probe is not None else (2048, 2048)
        slots, stripW, stripH, subsample, dx = prescanLayout(
            span, dx, pixelSize, frameShape, subsample,
            self.PRESCAN_MAX_STRIP_MB * 1024 * 1024)
        scale = pixelSize * subsample
        strip = None  # allocated from the first frame: its dtype is the camera's
        lastFrameNumber = -1
        newFrames = 0

        mover = _NonBlockingMove(self._stage, endX - startX, "X", speedX)
        mover.start()
        started = time.time()
        # A hung move never sets finished (the serial bus can block), so the
        # loop is also bounded by how long the sweep could possibly take.
        deadline = started + (span / max(speedX, 1e-6)) * 3.0 + 10.0

        k = 0
        while k < slots and not self._shouldStop.is_set() and time.time() < deadline:
            due = started + k * dx / speedX
            now = time.time()
            if now < due:
                if mover.finished:
                    break  # the stage arrived early: the tail stays empty rather than smeared
                time.sleep(min(0.005, due - now))
                continue
            try:
                frame, frameNumber = self._detector.getLatestFrame(returnFrameNumber=True)
            except TypeError:
                frame, frameNumber = self._detector.getLatestFrame(), lastFrameNumber + 1
            if frame is None or getattr(frame, "size", 0) == 0:
                time.sleep(0.005)
                continue
            if frameNumber != lastFrameNumber:
                newFrames += 1
                lastFrameNumber = frameNumber
            c0 = int(round(k * dx / scale))
            c1 = min(stripW, int(round((k + 1) * dx / scale)))
            if c1 > c0:
                band = self._centreBand(frame, (c1 - c0) * subsample, subsample)
                if strip is None:
                    strip = np.zeros((band.shape[0], stripW), dtype=band.dtype)
                width = min(c1 - c0, band.shape[1])
                strip[:band.shape[0], c0:c0 + width] = band[:, :width]
            k += 1

        mover.join(timeout=5.0)
        if mover.error:
            self._logger.error(f"Prescan line y={y:.0f}: move failed: {mover.error}")
            return None
        if not mover.finished:
            self._logger.error(f"Prescan line y={y:.0f}: move did not finish in time")
            return None
        if strip is None or k < 2:
            self._logger.warning(f"Prescan line y={y:.0f}: only {k} exposure(s)")
            return None
        if newFrames < k:
            # The camera could not serve one frame per slot, so neighbouring
            # slots repeated a frame. Say what speed it CAN keep up with.
            elapsed = max(time.time() - started, 1e-3)
            fps = newFrames / elapsed
            self._logger.warning(
                f"Prescan line y={y:.0f}: {newFrames} frames for {k} slots — "
                f"a frame every {dx / speedX * 1000:.0f} ms is needed at {speedX:.0f} µm/s; "
                f"this camera keeps up to about {fps * dx:.0f} µm/s")
        return strip, scale

    def _addStrip(self, strip: np.ndarray, minX: float, maxX: float, y: float,
                  pixelSize: float):
        """Push one prescan line into the existing tile store as a wide tile.

        ``pixelSize`` is the strip's own µm/px (coarser than the camera's).
        """
        preview = self._makePreview(strip)
        if preview is None:
            return
        with self._tilesLock:
            tileId = len(self._tiles)
        tile = {
            "id": tileId,
            "x": float((minX + maxX) / 2.0),
            "y": float(y),
            "widthUm": float(maxX - minX),
            "heightUm": float(strip.shape[0] * pixelSize),
            "channel": self._getActiveChannel(),
            "rawPath": "",
            "timestamp": time.time(),
            "preview": preview,
        }
        with self._tilesLock:
            self._tiles.append(tile)
            self._trimTiles()
        self._writeTileIndex()
        self.sigStageMapTileAdded.emit({
            "id": tileId, "x": tile["x"], "y": tile["y"],
            "widthUm": tile["widthUm"], "heightUm": tile["heightUm"],
            "channel": tile["channel"], "image": preview, "format": "jpeg",
        })

    # ------------------------------------------------------------------ #
    # Monitor loop
    # ------------------------------------------------------------------ #

    def _minMoveDistanceUm(self) -> float:
        pixelSize = self._getPixelSizeUm()
        fov = 0.0
        try:
            if self._detector is not None:
                shape = self._detector.shape
                fov = min(shape[0], shape[1]) * pixelSize
        except Exception:
            pass
        if fov <= 0:
            fov = 100.0
        return max(1.0, float(self.params.minMoveFraction) * fov)

    def _lastTilePositionForChannel(self, channel: str) -> Optional[List[float]]:
        with self._tilesLock:
            for tile in reversed(self._tiles):
                if tile["channel"] == channel:
                    return [tile["x"], tile["y"]]
        return None

    def _needsTileAt(self, position: List[float], channel: str) -> bool:
        """True when no tile of this channel is close enough to `position`."""
        minDist = self._minMoveDistanceUm()
        with self._tilesLock:
            for tile in self._tiles:
                if tile["channel"] != channel:
                    continue
                if (abs(tile["x"] - position[0]) < minDist
                        and abs(tile["y"] - position[1]) < minDist):
                    return False
        return True

    def _monitorLoop(self):
        lastPos = None
        stationarySince = None
        epsilon = 0.5  # µm - jitter tolerance for "stage is stationary"

        # snap immediately where we are - "always start from where we currently are"
        startPos = self._getStagePositionXY()
        if startPos is not None:
            self._captureTile(startPos)
            lastPos = startPos

        while not self._shouldStop.is_set():
            time.sleep(max(0.02, float(self.params.positionPollS)))

            pos = self._getStagePositionXY()
            if pos is None:
                continue

            # manual snap request from the frontend
            if self._snapRequested.is_set():
                self._snapRequested.clear()
                self._captureTile(pos)
                lastPos = pos
                stationarySince = None
                continue

            if not self.params.autoSnapEnabled:
                lastPos = pos
                continue

            if lastPos is not None and (abs(pos[0] - lastPos[0]) < epsilon
                                        and abs(pos[1] - lastPos[1]) < epsilon):
                if stationarySince is None:
                    stationarySince = time.time()
                elif time.time() - stationarySince >= float(self.params.settleTimeS):
                    channel = self._getActiveChannel()
                    if self._needsTileAt(pos, channel):
                        self._captureTile(pos)
                    # keep stationarySince so we don't retrigger while parked;
                    # _needsTileAt() blocks duplicates anyway
            else:
                stationarySince = None
            lastPos = pos

        self._logger.debug("Stage map monitor loop finished")

    def _emitStatus(self):
        try:
            self.sigStageMapStatus.emit(self.getStageMapStatus().dict())
        except Exception:
            pass

    # ------------------------------------------------------------------ #
    # API
    # ------------------------------------------------------------------ #

    @APIExport()
    def getStageMapParams(self) -> StageMapParams:
        """Get the current stage map parameters."""
        return self.params

    @APIExport(requestType="POST")
    def setStageMapParams(self, params: StageMapParams) -> bool:
        """Set stage map parameters."""
        self.params = params
        self._emitStatus()
        return True

    @APIExport()
    def getStageMapStatus(self) -> StageMapStatus:
        """Get runtime status (position, FOV, tile count, channels)."""
        pos = self._getStagePositionXY() or [0.0, 0.0]
        pixelSize = self._getPixelSizeUm()
        fovX = fovY = 0.0
        try:
            if self._detector is not None:
                shape = self._detector.shape
                # DetectorManager.shape is (width, height) for most cameras;
                # report both so the frontend can draw the FOV rectangle.
                fovX = float(shape[0]) * pixelSize
                fovY = float(shape[1]) * pixelSize
        except Exception:
            pass
        with self._tilesLock:
            tileCount = len(self._tiles)
            channels = sorted({t["channel"] for t in self._tiles})
        return StageMapStatus(
            isRunning=self._isRunning,
            sessionPath=self._sessionPath or "",
            tileCount=tileCount,
            channels=channels,
            activeChannel=self._getActiveChannel(),
            pixelSizeUm=pixelSize,
            fovX=fovX,
            fovY=fovY,
            positionX=pos[0],
            positionY=pos[1],
            detectorName=self._detectorName,
            lastError=self._lastError,
        )

    @APIExport()
    def startStageMap(self) -> bool:
        """Start mapping: tiles are captured wherever the stage settles."""
        if self._isRunning:
            return False
        if self._detector is None or self._stage is None:
            self._lastError = "Detector or stage not available"
            self._logger.error(self._lastError)
            return False

        if self._sessionPath is None:
            self._createSession()

        try:
            self._acqHandle = self._master.detectorsManager.startAcquisition()
        except Exception as e:
            self._logger.warning(f"Could not start acquisition (may already run): {e}")
            self._acqHandle = None

        self._lastError = ""
        self._shouldStop.clear()
        self._snapRequested.clear()
        self._isRunning = True
        self._monitorThread = threading.Thread(target=self._monitorLoop, daemon=True)
        self._monitorThread.start()
        self._emitStatus()
        self._logger.info("Stage map started")
        return True

    @APIExport(requestType="POST")
    def startPrescan(self, minX: float, maxX: float, minY: float, maxY: float,
                     dy: float = 500.0, speedX: float = 10000.0,
                     objectiveSlot: Optional[int] = None,
                     dx: float = 0.0, subsample: int = 0) -> Dict:
        """Sweep an area fast and drop the result on the map as an overlay.

        The stage runs continuously in X while the camera free-runs; frames are
        re-spaced along X from elapsed time, downsampled, and pushed into the
        SAME tile store the stage map uses, one strip per Y line. Coarse in Y
        and motion-blurred in X on purpose: this is a locator for finding
        tissue, not data.

        Illumination, exposure and gain are used exactly as the operator left
        them. Nothing here switches channels or auto-exposes, and nothing
        should be added that does.

        Coordinates are stage micrometres throughout, so a prescan taken with a
        10x objective lines up with a 20x acquisition without rescaling.

        Lines are driven in a serpentine, and each strip is emitted over the
        socket the moment its line finishes, so the map fills in as it goes.

        ``objectiveSlot`` switches the turret before the sweep (its own saved
        focus comes with it) and everything — objective, X, Y and Z — is put
        back afterwards. The caller is expected to have asked the operator
        first: moving the turret is a physical change.

        ``dx`` is the exposure pitch along the sweep in µm — the same tile
        spacing the scan uses; 0 means one field width. ``subsample`` is
        camera pixels per strip pixel (0 = the default); the strip grows
        coarser on its own if it would exceed ``PRESCAN_MAX_STRIP_MB``.
        """
        if self._isRunning or self._prescanThread is not None:
            return {"success": False, "error": "A scan is already running"}
        if self._detector is None or self._stage is None:
            return {"success": False, "error": "Detector or stage not available"}
        if maxX <= minX or maxY < minY or dy <= 0 or speedX <= 0:
            return {"success": False, "error": "Invalid area, dy or speed"}

        if self._sessionPath is None:
            self._createSession()
        self._shouldStop.clear()
        self._prescanThread = threading.Thread(
            target=self._prescanLoop,
            args=(float(minX), float(maxX), float(minY), float(maxY),
                  float(dy), float(speedX),
                  None if objectiveSlot is None else int(objectiveSlot),
                  float(dx), int(subsample) or self.PRESCAN_SUBSAMPLE),
            daemon=True,
        )
        self._prescanThread.start()
        nLines = int((maxY - minY) / dy) + 1
        self._logger.info(
            f"Prescan started: X {minX:.0f}->{maxX:.0f} um, {nLines} line(s) "
            f"every {dy:.0f} um at {speedX:.0f} um/s"
        )
        return {"success": True, "lines": nLines}

    @APIExport()
    def getStageMapOverview(self, maxWidthPx: int = 2048) -> Dict:
        """The whole map as one image plus the stage extent it covers.

        For consumers outside the React app (napari, a notebook, a script):
        everything is in stage micrometres, so an overview taken at 10x can be
        used to plan an acquisition at 20x without rescaling anything.

        Returns ``image`` (base64 JPEG), ``bounds`` (min/max X/Y in um) and
        ``umPerPixel`` — position in um = bounds.minX + column * umPerPixel.
        """
        with self._tilesLock:
            tiles = [t for t in self._tiles if t.get("preview")]
        if not tiles:
            return {"success": False, "error": "No tiles captured yet"}

        minX = min(t["x"] - t["widthUm"] / 2 for t in tiles)
        maxX = max(t["x"] + t["widthUm"] / 2 for t in tiles)
        minY = min(t["y"] - t["heightUm"] / 2 for t in tiles)
        maxY = max(t["y"] + t["heightUm"] / 2 for t in tiles)
        spanX, spanY = maxX - minX, maxY - minY
        if spanX <= 0 or spanY <= 0:
            return {"success": False, "error": "Empty map extent"}

        umPerPixel = max(spanX / max(1, int(maxWidthPx)), self._getPixelSizeUm())
        width = max(1, int(round(spanX / umPerPixel)))
        height = max(1, int(round(spanY / umPerPixel)))
        canvas = np.zeros((height, width), dtype=np.uint8)

        for tile in tiles:
            img = self._decodePreview(tile["preview"])
            if img is None:
                continue
            tw = max(1, int(round(tile["widthUm"] / umPerPixel)))
            th = max(1, int(round(tile["heightUm"] / umPerPixel)))
            img = self._resizeGray(img, tw, th)
            x0 = int(round((tile["x"] - tile["widthUm"] / 2 - minX) / umPerPixel))
            y0 = int(round((tile["y"] - tile["heightUm"] / 2 - minY) / umPerPixel))
            x1, y1 = min(width, x0 + tw), min(height, y0 + th)
            x0, y0 = max(0, x0), max(0, y0)
            if x1 > x0 and y1 > y0:
                canvas[y0:y1, x0:x1] = img[: y1 - y0, : x1 - x0]

        encoded = self._makePreview(canvas)
        if encoded is None:
            return {"success": False, "error": "Could not encode overview"}
        return {
            "success": True,
            "image": encoded,
            "format": "jpeg",
            "widthPx": width,
            "heightPx": height,
            "umPerPixel": float(umPerPixel),
            "bounds": {"minX": float(minX), "maxX": float(maxX),
                       "minY": float(minY), "maxY": float(maxY)},
            "tileCount": len(tiles),
        }

    def _decodePreview(self, preview: str) -> Optional[np.ndarray]:
        """base64 JPEG -> 2-D uint8 array."""
        try:
            raw = base64.b64decode(preview)
            if HAS_CV2:
                return cv2.imdecode(np.frombuffer(raw, np.uint8), cv2.IMREAD_GRAYSCALE)
            from PIL import Image
            import io
            return np.array(Image.open(io.BytesIO(raw)).convert("L"))
        except Exception as e:
            self._logger.debug(f"Could not decode tile preview: {e}")
            return None

    @staticmethod
    def _resizeGray(img: np.ndarray, width: int, height: int) -> np.ndarray:
        if img.shape[0] == height and img.shape[1] == width:
            return img
        if HAS_CV2:
            return cv2.resize(img, (width, height), interpolation=cv2.INTER_AREA)
        ys = (np.linspace(0, img.shape[0] - 1, height)).astype(int)
        xs = (np.linspace(0, img.shape[1] - 1, width)).astype(int)
        return img[np.ix_(ys, xs)]

    @APIExport()
    def stopPrescan(self) -> bool:
        """Stop a running prescan; strips already produced are kept."""
        self._shouldStop.set()
        if self._prescanThread is not None and self._prescanThread.is_alive():
            self._prescanThread.join(timeout=10.0)
        self._prescanThread = None
        return True

    @APIExport()
    def stopStageMap(self) -> bool:
        """Stop mapping (the collected map is kept)."""
        if not self._isRunning:
            return False
        self._shouldStop.set()
        if self._monitorThread is not None and self._monitorThread.is_alive():
            self._monitorThread.join(timeout=5.0)
        self._isRunning = False
        if self._acqHandle is not None:
            try:
                self._master.detectorsManager.stopAcquisition(self._acqHandle)
            except Exception:
                pass
            self._acqHandle = None
        self._emitStatus()
        self._logger.info("Stage map stopped")
        return True

    @APIExport()
    def snapStageMapTile(self) -> bool:
        """Capture a tile at the current position right now (manual snap)."""
        if self._isRunning:
            self._snapRequested.set()
            return True
        # allow one-shot snaps while mapping is stopped
        if self._sessionPath is None:
            self._createSession()
        pos = self._getStagePositionXY()
        if pos is None:
            return False
        handle = None
        try:
            handle = self._master.detectorsManager.startAcquisition()
        except Exception:
            pass
        try:
            return self._captureTile(pos)
        finally:
            if handle is not None:
                try:
                    self._master.detectorsManager.stopAcquisition(handle)
                except Exception:
                    pass

    @APIExport()
    def clearStageMap(self) -> bool:
        """Discard the current map and start a fresh session."""
        self._sessionPath = None
        with self._tilesLock:
            self._tiles = []
        self._emitStatus()
        return True

    @APIExport()
    def setStageMapChannel(self, channel: str = "") -> bool:
        """Set the channel label for the next tiles (empty = auto-detect)."""
        self.params.activeChannel = channel
        self._emitStatus()
        return True

    @APIExport()
    def getStageMapTiles(self, fromId: int = 0, includePreviews: bool = True) -> Dict:
        """Return tile metadata (and previews) so the frontend can rebuild the map."""
        with self._tilesLock:
            tiles = []
            for tile in self._tiles:
                if tile["id"] < fromId:
                    continue
                entry = {
                    "id": tile["id"],
                    "x": tile["x"],
                    "y": tile["y"],
                    "widthUm": tile["widthUm"],
                    "heightUm": tile["heightUm"],
                    "channel": tile["channel"],
                    "timestamp": tile["timestamp"],
                }
                if includePreviews:
                    entry["image"] = tile["preview"]
                    entry["format"] = "jpeg"
                tiles.append(entry)
        return {"tiles": tiles, "sessionPath": self._sessionPath or ""}

    @APIExport()
    def gotoStagePosition(self, x: float, y: float, isAbsolute: bool = True,
                          isBlocking: bool = False) -> bool:
        """Move the XY stage (used for map double-click / arrow-key navigation).

        With isBlocking=True the call returns only after the move finished, so
        the caller can immediately snap a tile at the settled position.
        """
        if self._stage is None:
            return False
        try:
            self._stage.move((float(x), float(y)), "XY", is_absolute=isAbsolute,
                             is_blocking=isBlocking)
            return True
        except Exception as e:
            self._logger.error(f"Could not move stage: {e}")
            return False

    @APIExport()
    def saveStitchedOmeTiff(self, filename: str = "") -> Dict:
        """Fuse all raw tiles into a multi-channel stitched OME-TIFF.

        Tiles are placed on a common canvas in stage coordinates
        (last-written-wins in overlap regions). One OME channel per
        illumination channel. Returns the file path.
        """
        if not HAS_TIFFFILE:
            return {"success": False, "error": "tifffile not available"}
        if not self._sessionPath:
            return {"success": False, "error": "No active session"}

        with self._tilesLock:
            tiles = [t for t in self._tiles if t.get("rawPath") and os.path.exists(t["rawPath"])]
        if not tiles:
            return {"success": False, "error": "No raw tiles stored (enable saveRawTiles)"}

        pixelSize = self._getPixelSizeUm()
        channels = sorted({t["channel"] for t in tiles})

        # Canvas extent in stage coordinates (tile x/y is the FOV centre)
        minX = min(t["x"] - t["widthUm"] / 2 for t in tiles)
        maxX = max(t["x"] + t["widthUm"] / 2 for t in tiles)
        minY = min(t["y"] - t["heightUm"] / 2 for t in tiles)
        maxY = max(t["y"] + t["heightUm"] / 2 for t in tiles)
        canvasW = int(np.ceil((maxX - minX) / pixelSize))
        canvasH = int(np.ceil((maxY - minY) / pixelSize))

        if canvasW <= 0 or canvasH <= 0:
            return {"success": False, "error": "Empty canvas extent"}
        if float(canvasW) * canvasH * len(channels) > self.MAX_STITCH_PIXELS:
            return {
                "success": False,
                "error": f"Stitched canvas too large ({canvasW}x{canvasH}x{len(channels)} px). "
                         f"Reduce the mapped area or number of channels.",
            }

        # Determine dtype from the first tile
        firstFrame = tifffile.imread(tiles[0]["rawPath"])
        dtype = firstFrame.dtype
        isColor = firstFrame.ndim == 3

        try:
            if isColor:
                # colour cameras: stitch as RGB, ignore channel separation
                canvas = np.zeros((canvasH, canvasW, firstFrame.shape[2]), dtype=dtype)
                stack = None
            else:
                stack = np.zeros((len(channels), canvasH, canvasW), dtype=dtype)
                canvas = None
        except MemoryError:
            return {"success": False, "error": "Not enough memory for stitched canvas"}

        for tile in tiles:
            try:
                frame = tifffile.imread(tile["rawPath"])
            except Exception as e:
                self._logger.warning(f"Skipping unreadable tile {tile['rawPath']}: {e}")
                continue
            h, w = frame.shape[0], frame.shape[1]
            # top-left pixel of this tile on the canvas
            px = int(round((tile["x"] - tile["widthUm"] / 2 - minX) / pixelSize))
            py = int(round((tile["y"] - tile["heightUm"] / 2 - minY) / pixelSize))
            px0, py0 = max(0, px), max(0, py)
            px1, py1 = min(canvasW, px + w), min(canvasH, py + h)
            if px1 <= px0 or py1 <= py0:
                continue
            fx0, fy0 = px0 - px, py0 - py
            if isColor:
                canvas[py0:py1, px0:px1, :] = frame[fy0:fy0 + (py1 - py0), fx0:fx0 + (px1 - px0), :]
            else:
                ci = channels.index(tile["channel"])
                stack[ci, py0:py1, px0:px1] = frame[fy0:fy0 + (py1 - py0), fx0:fx0 + (px1 - px0)]

        if not filename:
            filename = datetime.now().strftime("stagemap_stitched_%Y%m%d_%H%M%S.ome.tif")
        if not filename.endswith((".ome.tif", ".ome.tiff")):
            filename += ".ome.tif"
        outPath = os.path.join(self._sessionPath, filename)

        try:
            if isColor:
                tifffile.imwrite(
                    outPath, canvas, ome=True,
                    metadata={
                        "axes": "YXS",
                        "PhysicalSizeX": pixelSize, "PhysicalSizeXUnit": "µm",
                        "PhysicalSizeY": pixelSize, "PhysicalSizeYUnit": "µm",
                    },
                )
            else:
                tifffile.imwrite(
                    outPath, stack, ome=True,
                    metadata={
                        "axes": "CYX",
                        "Channel": {"Name": channels},
                        "PhysicalSizeX": pixelSize, "PhysicalSizeXUnit": "µm",
                        "PhysicalSizeY": pixelSize, "PhysicalSizeYUnit": "µm",
                    },
                )
        except Exception as e:
            self._logger.error(f"Could not write stitched OME-TIFF: {e}")
            return {"success": False, "error": str(e)}

        self._logger.info(f"Stitched OME-TIFF written to {outPath}")
        return {
            "success": True,
            "path": outPath,
            "widthPx": canvasW,
            "heightPx": canvasH,
            "channels": channels,
        }

    def __del__(self):
        try:
            self._shouldStop.set()
        except Exception:
            pass


# Copyright (C) 2020-2026 ImSwitch developers
# This file is part of ImSwitch.
#
# ImSwitch is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ImSwitch is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
