import base64
import json
import os
import threading
import time
from datetime import datetime
from typing import Dict, List, Optional

import numpy as np
from pydantic import BaseModel

from imswitch.imcommon.framework import Signal
from imswitch.imcommon.model import APIExport, dirtools, initLogger
from ..basecontrollers import ImConWidgetController

try:
    import cv2
    HAS_CV2 = True
except ImportError:
    HAS_CV2 = False

try:
    import tifffile
    HAS_TIFFFILE = True
except ImportError:
    HAS_TIFFFILE = False


class StageMapParams(BaseModel):
    """Parameters for the stage map (MicroMagellan-style live stitching)."""
    # Capture behaviour
    autoSnapEnabled: bool = True        # snap automatically when the stage settled at a new spot
    minMoveFraction: float = 0.35       # min displacement (fraction of the smaller FOV side) to trigger a new tile
    settleTimeS: float = 0.25           # stage must be stationary for this long before a snap
    positionPollS: float = 0.15         # position polling interval
    frameTimeoutS: float = 2.0          # max time to wait for a fresh frame after settling

    # Preview (what is pushed to the frontend)
    previewMaxSize: int = 384           # longest side of the downscaled preview tile in px
    previewQuality: int = 80            # JPEG quality of preview tiles

    # Storage
    saveRawTiles: bool = True           # store full-resolution raw frames on disk
    mapName: str = ""                   # session name; autogenerated when empty

    # Optics; 0 means "read from detector"
    pixelSizeUm: float = 0.0

    # Channel handling
    activeChannel: str = ""             # empty = auto-detect from enabled illumination

    class Config:
        arbitrary_types_allowed = True


class StageMapStatus(BaseModel):
    """Runtime status of the stage map."""
    isRunning: bool = False
    sessionPath: str = ""
    tileCount: int = 0
    channels: List[str] = []
    activeChannel: str = ""
    pixelSizeUm: float = 1.0
    fovX: float = 0.0                   # camera FOV in µm
    fovY: float = 0.0
    positionX: float = 0.0
    positionY: float = 0.0
    detectorName: str = ""
    lastError: str = ""

    class Config:
        arbitrary_types_allowed = True


class StageMapController(ImConWidgetController):
    """MicroMagellan/Google-Maps-style stage mapping.

    While mapping is running, the controller watches the stage position.
    Whenever the stage comes to rest at a spot that is not covered yet
    (or covered by an older tile), it grabs a camera frame, stores the raw
    frame on disk, and pushes a downscaled JPEG preview to the frontend via
    the ``sigStageMapTileAdded`` socket signal. The frontend places the
    previews on a pan/zoom canvas in stage coordinates, so a stitched map
    grows wherever the user moves — no extra stage movement is generated.

    The full-resolution tiles can be fused into a multi-channel stitched
    OME-TIFF via ``saveStitchedOmeTiff``.
    """

    sigStageMapTileAdded = Signal(dict)
    sigStageMapStatus = Signal(dict)

    MAX_STITCH_PIXELS = 1.2e9  # safety cap for the stitched canvas (bytes ~ 2x for uint16)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._logger = initLogger(self)

        self.params = StageMapParams()

        # Hardware
        self._detector = None
        self._detectorName = ""
        self._stage = None
        self._initializeHardware()

        # Session/tile state
        self._tiles: List[Dict] = []          # metadata for every captured tile
        self._tilesLock = threading.Lock()
        self._sessionPath: Optional[str] = None
        self._acqHandle = None

        # Mapping thread state
        self._isRunning = False
        self._shouldStop = threading.Event()
        self._monitorThread: Optional[threading.Thread] = None
        self._snapRequested = threading.Event()
        self._lastError = ""

        self._logger.info("StageMapController initialized")

    # ------------------------------------------------------------------ #
    # Hardware helpers
    # ------------------------------------------------------------------ #

    def _initializeHardware(self):
        try:
            detectorNames = self._master.detectorsManager.getAllDeviceNames()
            if detectorNames:
                try:
                    self._detectorName = self._master.detectorsManager.getCurrentDetectorName()
                except Exception:
                    self._detectorName = detectorNames[0]
                self._detector = self._master.detectorsManager[self._detectorName]
        except Exception as e:
            self._logger.warning(f"No detector available for stage map: {e}")

        try:
            positionerNames = self._master.positionersManager.getAllDeviceNames()
            if positionerNames:
                self._stage = self._master.positionersManager[positionerNames[0]]
        except Exception as e:
            self._logger.warning(f"No positioner available for stage map: {e}")

    def _getPixelSizeUm(self) -> float:
        if self.params.pixelSizeUm and self.params.pixelSizeUm > 0:
            return float(self.params.pixelSizeUm)
        try:
            # DetectorManager.pixelSizeUm is [Z, Y, X]
            ps = self._detector.pixelSizeUm
            pixelSize = float(ps[-1])
            if pixelSize > 0:
                return pixelSize
        except Exception:
            pass
        return 1.0

    def _getStagePositionXY(self) -> Optional[List[float]]:
        try:
            pos = self._stage.getPosition()
            return [float(pos.get("X", 0.0)), float(pos.get("Y", 0.0))]
        except Exception as e:
            self._logger.error(f"Could not read stage position: {e}")
            return None

    def _getActiveChannel(self) -> str:
        """Explicit channel wins; otherwise derive from enabled illumination."""
        if self.params.activeChannel:
            return self.params.activeChannel
        try:
            for laserName in self._master.lasersManager.getAllDeviceNames():
                laser = self._master.lasersManager[laserName]
                if getattr(laser, "enabled", False):
                    return str(laserName)
        except Exception:
            pass
        return "default"

    def _grabFreshFrame(self) -> Optional[np.ndarray]:
        """Grab a frame that was exposed after the stage settled."""
        if self._detector is None:
            return None
        try:
            if hasattr(self._detector, "flushBuffer"):
                self._detector.flushBuffer()
            elif hasattr(self._detector, "flushBuffers"):
                self._detector.flushBuffers()
        except Exception:
            pass

        timeout = max(0.2, float(self.params.frameTimeoutS))
        t0 = time.time()
        lastFrameNumber = -1
        frame = None
        while time.time() - t0 < timeout:
            try:
                frame, frameNumber = self._detector.getLatestFrame(returnFrameNumber=True)
            except TypeError:
                # Detector does not support frame numbers - accept the latest frame
                frame = self._detector.getLatestFrame()
                if frame is not None:
                    return frame
                time.sleep(0.02)
                continue
            except Exception as e:
                self._logger.error(f"Error grabbing frame: {e}")
                return None
            if frame is not None and frameNumber is not None:
                if lastFrameNumber == -1:
                    lastFrameNumber = frameNumber
                elif frameNumber > lastFrameNumber:
                    return frame
            time.sleep(0.02)
        return frame

    # ------------------------------------------------------------------ #
    # Session / storage
    # ------------------------------------------------------------------ #

    def _createSession(self):
        name = self.params.mapName.strip() or datetime.now().strftime("stagemap_%Y%m%d_%H%M%S")
        base = os.path.join(dirtools.UserFileDirs.getValidatedDataPath(), "StageMapController", name)
        os.makedirs(os.path.join(base, "raw"), exist_ok=True)
        self._sessionPath = base
        with self._tilesLock:
            self._tiles = []
        self._writeTileIndex()
        self._logger.info(f"Stage map session created at {base}")

    def _writeTileIndex(self):
        if not self._sessionPath:
            return
        try:
            with self._tilesLock:
                index = {
                    "pixelSizeUm": self._getPixelSizeUm(),
                    "tiles": [
                        {k: v for k, v in t.items() if k != "preview"}
                        for t in self._tiles
                    ],
                }
            with open(os.path.join(self._sessionPath, "tiles.json"), "w") as f:
                json.dump(index, f, indent=2)
        except Exception as e:
            self._logger.error(f"Could not write tile index: {e}")

    def _makePreview(self, frame: np.ndarray) -> Optional[str]:
        """Downscale + JPEG-encode a frame, return base64 string."""
        try:
            img = frame
            if img.ndim == 3:
                # colour camera: keep as-is (assume BGR/RGB uint8)
                pass
            maxSide = max(img.shape[0], img.shape[1])
            scale = min(1.0, float(self.params.previewMaxSize) / maxSide)
            if HAS_CV2:
                if scale < 1.0:
                    img = cv2.resize(
                        img,
                        (max(1, int(img.shape[1] * scale)), max(1, int(img.shape[0] * scale))),
                        interpolation=cv2.INTER_AREA,
                    )
                # normalize to 8 bit for the preview
                if img.dtype != np.uint8:
                    img = img.astype(np.float32)
                    lo, hi = np.percentile(img, (1, 99.8))
                    if hi <= lo:
                        hi = lo + 1
                    img = np.clip((img - lo) / (hi - lo) * 255.0, 0, 255).astype(np.uint8)
                ok, buf = cv2.imencode(
                    ".jpg", img, [int(cv2.IMWRITE_JPEG_QUALITY), int(self.params.previewQuality)]
                )
                if not ok:
                    return None
                return base64.b64encode(buf.tobytes()).decode("ascii")
            else:
                # numpy-only fallback: subsample + PNG via tifffile is overkill; use PIL if present
                from PIL import Image
                import io
                if scale < 1.0:
                    step = max(1, int(round(1.0 / scale)))
                    img = img[::step, ::step]
                if img.dtype != np.uint8:
                    img = img.astype(np.float32)
                    lo, hi = np.percentile(img, (1, 99.8))
                    if hi <= lo:
                        hi = lo + 1
                    img = np.clip((img - lo) / (hi - lo) * 255.0, 0, 255).astype(np.uint8)
                pil = Image.fromarray(img)
                bio = io.BytesIO()
                pil.save(bio, format="JPEG", quality=int(self.params.previewQuality))
                return base64.b64encode(bio.getvalue()).decode("ascii")
        except Exception as e:
            self._logger.error(f"Could not create preview: {e}")
            return None

    # ------------------------------------------------------------------ #
    # Tile capture
    # ------------------------------------------------------------------ #

    def _captureTile(self, position: List[float]) -> bool:
        frame = self._grabFreshFrame()
        if frame is None:
            self._lastError = "No frame received from detector"
            self._logger.warning(self._lastError)
            return False

        pixelSize = self._getPixelSizeUm()
        channel = self._getActiveChannel()
        heightPx, widthPx = frame.shape[0], frame.shape[1]
        widthUm = widthPx * pixelSize
        heightUm = heightPx * pixelSize

        with self._tilesLock:
            tileId = len(self._tiles)

        rawPath = ""
        if self.params.saveRawTiles and self._sessionPath and HAS_TIFFFILE:
            try:
                safeChannel = "".join(c if c.isalnum() else "_" for c in channel)
                rawPath = os.path.join(
                    self._sessionPath, "raw",
                    f"tile_{tileId:05d}_{safeChannel}.tif",
                )
                tifffile.imwrite(
                    rawPath,
                    frame,
                    metadata={
                        "PositionX_um": position[0],
                        "PositionY_um": position[1],
                        "PixelSize_um": pixelSize,
                        "Channel": channel,
                    },
                )
            except Exception as e:
                self._logger.error(f"Could not save raw tile: {e}")
                rawPath = ""

        preview = self._makePreview(frame)

        tile = {
            "id": tileId,
            # centre of the FOV in stage coordinates (µm)
            "x": float(position[0]),
            "y": float(position[1]),
            "widthUm": float(widthUm),
            "heightUm": float(heightUm),
            "channel": channel,
            "rawPath": rawPath,
            "timestamp": time.time(),
            "preview": preview,
        }
        with self._tilesLock:
            self._tiles.append(tile)
        self._writeTileIndex()

        if preview is not None:
            self.sigStageMapTileAdded.emit({
                "id": tileId,
                "x": tile["x"],
                "y": tile["y"],
                "widthUm": tile["widthUm"],
                "heightUm": tile["heightUm"],
                "channel": channel,
                "image": preview,
                "format": "jpeg",
            })
        self._emitStatus()
        return True

    # ------------------------------------------------------------------ #
    # Monitor loop
    # ------------------------------------------------------------------ #

    def _minMoveDistanceUm(self) -> float:
        pixelSize = self._getPixelSizeUm()
        fov = 0.0
        try:
            if self._detector is not None:
                shape = self._detector.shape
                fov = min(shape[0], shape[1]) * pixelSize
        except Exception:
            pass
        if fov <= 0:
            fov = 100.0
        return max(1.0, float(self.params.minMoveFraction) * fov)

    def _lastTilePositionForChannel(self, channel: str) -> Optional[List[float]]:
        with self._tilesLock:
            for tile in reversed(self._tiles):
                if tile["channel"] == channel:
                    return [tile["x"], tile["y"]]
        return None

    def _needsTileAt(self, position: List[float], channel: str) -> bool:
        """True when no tile of this channel is close enough to `position`."""
        minDist = self._minMoveDistanceUm()
        with self._tilesLock:
            for tile in self._tiles:
                if tile["channel"] != channel:
                    continue
                if (abs(tile["x"] - position[0]) < minDist
                        and abs(tile["y"] - position[1]) < minDist):
                    return False
        return True

    def _monitorLoop(self):
        lastPos = None
        stationarySince = None
        epsilon = 0.5  # µm - jitter tolerance for "stage is stationary"

        # snap immediately where we are - "always start from where we currently are"
        startPos = self._getStagePositionXY()
        if startPos is not None:
            self._captureTile(startPos)
            lastPos = startPos

        while not self._shouldStop.is_set():
            time.sleep(max(0.02, float(self.params.positionPollS)))

            pos = self._getStagePositionXY()
            if pos is None:
                continue

            # manual snap request from the frontend
            if self._snapRequested.is_set():
                self._snapRequested.clear()
                self._captureTile(pos)
                lastPos = pos
                stationarySince = None
                continue

            if not self.params.autoSnapEnabled:
                lastPos = pos
                continue

            if lastPos is not None and (abs(pos[0] - lastPos[0]) < epsilon
                                        and abs(pos[1] - lastPos[1]) < epsilon):
                if stationarySince is None:
                    stationarySince = time.time()
                elif time.time() - stationarySince >= float(self.params.settleTimeS):
                    channel = self._getActiveChannel()
                    if self._needsTileAt(pos, channel):
                        self._captureTile(pos)
                    # keep stationarySince so we don't retrigger while parked;
                    # _needsTileAt() blocks duplicates anyway
            else:
                stationarySince = None
            lastPos = pos

        self._logger.debug("Stage map monitor loop finished")

    def _emitStatus(self):
        try:
            self.sigStageMapStatus.emit(self.getStageMapStatus().dict())
        except Exception:
            pass

    # ------------------------------------------------------------------ #
    # API
    # ------------------------------------------------------------------ #

    @APIExport()
    def getStageMapParams(self) -> StageMapParams:
        """Get the current stage map parameters."""
        return self.params

    @APIExport(requestType="POST")
    def setStageMapParams(self, params: StageMapParams) -> bool:
        """Set stage map parameters."""
        self.params = params
        self._emitStatus()
        return True

    @APIExport()
    def getStageMapStatus(self) -> StageMapStatus:
        """Get runtime status (position, FOV, tile count, channels)."""
        pos = self._getStagePositionXY() or [0.0, 0.0]
        pixelSize = self._getPixelSizeUm()
        fovX = fovY = 0.0
        try:
            if self._detector is not None:
                shape = self._detector.shape
                # DetectorManager.shape is (width, height) for most cameras;
                # report both so the frontend can draw the FOV rectangle.
                fovX = float(shape[0]) * pixelSize
                fovY = float(shape[1]) * pixelSize
        except Exception:
            pass
        with self._tilesLock:
            tileCount = len(self._tiles)
            channels = sorted({t["channel"] for t in self._tiles})
        return StageMapStatus(
            isRunning=self._isRunning,
            sessionPath=self._sessionPath or "",
            tileCount=tileCount,
            channels=channels,
            activeChannel=self._getActiveChannel(),
            pixelSizeUm=pixelSize,
            fovX=fovX,
            fovY=fovY,
            positionX=pos[0],
            positionY=pos[1],
            detectorName=self._detectorName,
            lastError=self._lastError,
        )

    @APIExport()
    def startStageMap(self) -> bool:
        """Start mapping: tiles are captured wherever the stage settles."""
        if self._isRunning:
            return False
        if self._detector is None or self._stage is None:
            self._lastError = "Detector or stage not available"
            self._logger.error(self._lastError)
            return False

        if self._sessionPath is None:
            self._createSession()

        try:
            self._acqHandle = self._master.detectorsManager.startAcquisition()
        except Exception as e:
            self._logger.warning(f"Could not start acquisition (may already run): {e}")
            self._acqHandle = None

        self._lastError = ""
        self._shouldStop.clear()
        self._snapRequested.clear()
        self._isRunning = True
        self._monitorThread = threading.Thread(target=self._monitorLoop, daemon=True)
        self._monitorThread.start()
        self._emitStatus()
        self._logger.info("Stage map started")
        return True

    @APIExport()
    def stopStageMap(self) -> bool:
        """Stop mapping (the collected map is kept)."""
        if not self._isRunning:
            return False
        self._shouldStop.set()
        if self._monitorThread is not None and self._monitorThread.is_alive():
            self._monitorThread.join(timeout=5.0)
        self._isRunning = False
        if self._acqHandle is not None:
            try:
                self._master.detectorsManager.stopAcquisition(self._acqHandle)
            except Exception:
                pass
            self._acqHandle = None
        self._emitStatus()
        self._logger.info("Stage map stopped")
        return True

    @APIExport()
    def snapStageMapTile(self) -> bool:
        """Capture a tile at the current position right now (manual snap)."""
        if self._isRunning:
            self._snapRequested.set()
            return True
        # allow one-shot snaps while mapping is stopped
        if self._sessionPath is None:
            self._createSession()
        pos = self._getStagePositionXY()
        if pos is None:
            return False
        handle = None
        try:
            handle = self._master.detectorsManager.startAcquisition()
        except Exception:
            pass
        try:
            return self._captureTile(pos)
        finally:
            if handle is not None:
                try:
                    self._master.detectorsManager.stopAcquisition(handle)
                except Exception:
                    pass

    @APIExport()
    def clearStageMap(self) -> bool:
        """Discard the current map and start a fresh session."""
        self._sessionPath = None
        with self._tilesLock:
            self._tiles = []
        self._emitStatus()
        return True

    @APIExport()
    def setStageMapChannel(self, channel: str = "") -> bool:
        """Set the channel label for the next tiles (empty = auto-detect)."""
        self.params.activeChannel = channel
        self._emitStatus()
        return True

    @APIExport()
    def getStageMapTiles(self, fromId: int = 0, includePreviews: bool = True) -> Dict:
        """Return tile metadata (and previews) so the frontend can rebuild the map."""
        with self._tilesLock:
            tiles = []
            for tile in self._tiles:
                if tile["id"] < fromId:
                    continue
                entry = {
                    "id": tile["id"],
                    "x": tile["x"],
                    "y": tile["y"],
                    "widthUm": tile["widthUm"],
                    "heightUm": tile["heightUm"],
                    "channel": tile["channel"],
                    "timestamp": tile["timestamp"],
                }
                if includePreviews:
                    entry["image"] = tile["preview"]
                    entry["format"] = "jpeg"
                tiles.append(entry)
        return {"tiles": tiles, "sessionPath": self._sessionPath or ""}

    @APIExport()
    def gotoStagePosition(self, x: float, y: float, isAbsolute: bool = True) -> bool:
        """Move the XY stage (used for map double-click navigation)."""
        if self._stage is None:
            return False
        try:
            self._stage.move((float(x), float(y)), "XY", is_absolute=isAbsolute, is_blocking=False)
            return True
        except Exception as e:
            self._logger.error(f"Could not move stage: {e}")
            return False

    @APIExport()
    def saveStitchedOmeTiff(self, filename: str = "") -> Dict:
        """Fuse all raw tiles into a multi-channel stitched OME-TIFF.

        Tiles are placed on a common canvas in stage coordinates
        (last-written-wins in overlap regions). One OME channel per
        illumination channel. Returns the file path.
        """
        if not HAS_TIFFFILE:
            return {"success": False, "error": "tifffile not available"}
        if not self._sessionPath:
            return {"success": False, "error": "No active session"}

        with self._tilesLock:
            tiles = [t for t in self._tiles if t.get("rawPath") and os.path.exists(t["rawPath"])]
        if not tiles:
            return {"success": False, "error": "No raw tiles stored (enable saveRawTiles)"}

        pixelSize = self._getPixelSizeUm()
        channels = sorted({t["channel"] for t in tiles})

        # Canvas extent in stage coordinates (tile x/y is the FOV centre)
        minX = min(t["x"] - t["widthUm"] / 2 for t in tiles)
        maxX = max(t["x"] + t["widthUm"] / 2 for t in tiles)
        minY = min(t["y"] - t["heightUm"] / 2 for t in tiles)
        maxY = max(t["y"] + t["heightUm"] / 2 for t in tiles)
        canvasW = int(np.ceil((maxX - minX) / pixelSize))
        canvasH = int(np.ceil((maxY - minY) / pixelSize))

        if canvasW <= 0 or canvasH <= 0:
            return {"success": False, "error": "Empty canvas extent"}
        if float(canvasW) * canvasH * len(channels) > self.MAX_STITCH_PIXELS:
            return {
                "success": False,
                "error": f"Stitched canvas too large ({canvasW}x{canvasH}x{len(channels)} px). "
                         f"Reduce the mapped area or number of channels.",
            }

        # Determine dtype from the first tile
        firstFrame = tifffile.imread(tiles[0]["rawPath"])
        dtype = firstFrame.dtype
        isColor = firstFrame.ndim == 3

        try:
            if isColor:
                # colour cameras: stitch as RGB, ignore channel separation
                canvas = np.zeros((canvasH, canvasW, firstFrame.shape[2]), dtype=dtype)
                stack = None
            else:
                stack = np.zeros((len(channels), canvasH, canvasW), dtype=dtype)
                canvas = None
        except MemoryError:
            return {"success": False, "error": "Not enough memory for stitched canvas"}

        for tile in tiles:
            try:
                frame = tifffile.imread(tile["rawPath"])
            except Exception as e:
                self._logger.warning(f"Skipping unreadable tile {tile['rawPath']}: {e}")
                continue
            h, w = frame.shape[0], frame.shape[1]
            # top-left pixel of this tile on the canvas
            px = int(round((tile["x"] - tile["widthUm"] / 2 - minX) / pixelSize))
            py = int(round((tile["y"] - tile["heightUm"] / 2 - minY) / pixelSize))
            px0, py0 = max(0, px), max(0, py)
            px1, py1 = min(canvasW, px + w), min(canvasH, py + h)
            if px1 <= px0 or py1 <= py0:
                continue
            fx0, fy0 = px0 - px, py0 - py
            if isColor:
                canvas[py0:py1, px0:px1, :] = frame[fy0:fy0 + (py1 - py0), fx0:fx0 + (px1 - px0), :]
            else:
                ci = channels.index(tile["channel"])
                stack[ci, py0:py1, px0:px1] = frame[fy0:fy0 + (py1 - py0), fx0:fx0 + (px1 - px0)]

        if not filename:
            filename = datetime.now().strftime("stagemap_stitched_%Y%m%d_%H%M%S.ome.tif")
        if not filename.endswith((".ome.tif", ".ome.tiff")):
            filename += ".ome.tif"
        outPath = os.path.join(self._sessionPath, filename)

        try:
            if isColor:
                tifffile.imwrite(
                    outPath, canvas, ome=True,
                    metadata={
                        "axes": "YXS",
                        "PhysicalSizeX": pixelSize, "PhysicalSizeXUnit": "µm",
                        "PhysicalSizeY": pixelSize, "PhysicalSizeYUnit": "µm",
                    },
                )
            else:
                tifffile.imwrite(
                    outPath, stack, ome=True,
                    metadata={
                        "axes": "CYX",
                        "Channel": {"Name": channels},
                        "PhysicalSizeX": pixelSize, "PhysicalSizeXUnit": "µm",
                        "PhysicalSizeY": pixelSize, "PhysicalSizeYUnit": "µm",
                    },
                )
        except Exception as e:
            self._logger.error(f"Could not write stitched OME-TIFF: {e}")
            return {"success": False, "error": str(e)}

        self._logger.info(f"Stitched OME-TIFF written to {outPath}")
        return {
            "success": True,
            "path": outPath,
            "widthPx": canvasW,
            "heightPx": canvasH,
            "channels": channels,
        }

    def __del__(self):
        try:
            self._shouldStop.set()
        except Exception:
            pass


# Copyright (C) 2020-2026 ImSwitch developers
# This file is part of ImSwitch.
#
# ImSwitch is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ImSwitch is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
