"""Side-view outlines of the linear objective turret, for ObjectiveTurretView.jsx.

Projects every triangle of the turret CAD export (``objective turret.glb``,
metres, z up) along +Y, unions them per part with shapely and writes the
outlines as SVG path data in millimetres (x = -model x, i.e. seen from +Y like
the CAD side view: 4x left, 20x right; z up; plate centre at x = 0).

    python scripts/turret_side_view.py "objective turret.glb" \
        > frontend/src/components/objectiveTurretOutline.js

Mesh indices are those of the current export (the GLB has no part names).
"""
import json
import struct
import sys

import numpy as np
from shapely import Polygon, box, union_all

# part -> (mesh indices, z band in mm the part is cut to, or None)
FIXED = {
    "pins": ([1, 2, 3], None),
    "plate": ([0], None),
}
OBJECTIVES = {
    "low": {  # 4x in its black adapter
        "adapter": ([10], None),
        "barrel": ([6], (28.3, 99)),  # the rest sits inside the adapter
    },
    "high": {  # 20x, threaded straight into the plate
        "barrel": ([9], (12.5, 59.2)),
        "ring": ([9], (59.2, 62.0)),
        "nose": ([9], (62.0, 99)),
    },
}


def meshes(path):
    data = open(path, "rb").read()
    offset, chunks = 12, []
    while offset < len(data):
        length, _ = struct.unpack_from("<I4s", data, offset)
        chunks.append(data[offset + 8:offset + 8 + length])
        offset += 8 + length
    gltf, blob = json.loads(chunks[0]), chunks[1]

    def accessor(index):
        acc = gltf["accessors"][index]
        view = gltf["bufferViews"][acc["bufferView"]]
        width = {"SCALAR": 1, "VEC3": 3}[acc["type"]]
        dtype = {5126: np.float32, 5125: np.uint32, 5123: np.uint16}[acc["componentType"]]
        values = np.frombuffer(blob, dtype=dtype, count=acc["count"] * width,
                               offset=view.get("byteOffset", 0) + acc.get("byteOffset", 0))
        return values.reshape(-1, width) if width > 1 else values

    for mesh in gltf["meshes"]:
        primitive = mesh["primitives"][0]
        yield (accessor(primitive["attributes"]["POSITION"]) * 1000,
               accessor(primitive["indices"]).reshape(-1, 3))


def silhouette(parts, band):
    triangles = []
    for vertices, faces in parts:
        xz = np.column_stack([-vertices[:, 0], vertices[:, 2]])
        triangles += [Polygon(t) for t in xz[faces] if Polygon(t).area > 1e-6]
    shape = union_all(triangles)
    if band:
        shape = shape.intersection(box(-99, band[0], 99, band[1]))
    return shape.simplify(0.02)


def path(shape):
    return " ".join(
        "M" + " L".join(f"{x:.2f} {z:.2f}" for x, z in p.exterior.coords[:-1]) + " Z"
        for p in getattr(shape, "geoms", [shape]) if p.area > 0.05)


def main(glb):
    all_meshes = list(meshes(glb))

    def shape(indices, band):
        return silhouette([all_meshes[i] for i in indices], band)

    print("// Generated by scripts/turret_side_view.py from the turret CAD (objective turret.glb):")
    print("// side view along +Y in mm, z up, plate centre at x = 0. Do not edit by hand.")
    print("export const TURRET_OUTLINE = {")
    for name, spec in FIXED.items():
        print(f'  {name}: "{path(shape(*spec))}",')
    for name, parts in OBJECTIVES.items():
        part = {p: shape(*spec) for p, spec in parts.items()}
        x0, _, x1, top = union_all(list(part.values())).bounds
        _, z0, _, z1 = part["barrel"].bounds
        print(f"  {name}: {{ axis: {(x0 + x1) / 2:.2f}, top: {top:.2f}, "
              f"labelZ: {(z0 + z1) / 2:.2f}, width: {x1 - x0:.2f}, parts: {{")
        for p, s in part.items():
            print(f'    {p}: "{path(s)}",')
        print("  } },")
    print("};")


if __name__ == "__main__":
    main(sys.argv[1])
