name: build-frontend

on:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - 'v*'
  pull_request:
  merge_group:
  workflow_dispatch:
    inputs:
      git-ref:
        description: 'Git ref (optional)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          # We check out the PR's HEAD commit instead of its merge commit for traceability when
          # determining the build output's version string; if the CI run isn't a PR, we'll just use
          # the default ref via an empty string:
          ref: ${{ github.event.pull_request.head.sha }}
          # This repo has tons of cruft in its history, so we try to only fetch files we actually need:
          fetch-depth: 0
          filter: 'blob:none'
          # We fetch tags so that the staged pallet bundle has a record of ancestral tags, for
          # pseudoversion string generation:
          fetch-tags: true

      - name: Use cached ~/.npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.variant }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node

      - name: Install build dependencies
        working-directory: ./frontend
        run: npm install

      - name: Determine version string
        id: version-string
        run: |
          TAG="$(git describe --tags --exact-match --match "v*")"
          VERSION="$(git describe --tags --match "v*" --abbrev=7
          TIMESTAMP="$(TZ=UTC git show -s --format=%ad --date=format:'%Y%m%d.%H%M%S')"

          if [[ "$VERSION" != "$TAG" ]]; then
            VERSION="$VERSION-$TIMESTAMP"
            if [[ -n "${{ github.event.pull_request.head.sha }}" ]]; then
              # We're in a pull request
              VERSION="$VERSION-pr${{ github.event.pull_request.number }}"
            fi
          fi

          echo "version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build
        working-directory: ./frontend
        run: |
          export NODE_OPTIONS=--max_old_space_size=4096
          CI=false npm run build

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: ./frontend/build
